(defn catch-errors 
   "A function that catches errors and returns an error message or the result of the function."
   [func]
   (fn
     ([] (try (func) 
              (catch Exception e (do (println "Error caught:" (. getMessage e))
                                     e))))
     ([arg] (try (func arg) 
                 (catch Exception e (do (println "Error caught:" (. getMessage e))
                                        e))))
     ([arg & more] (apply func arg more))))